version: '3'
services:
  api:
    container_name: api
    build: .
    restart: always
    env_file:
      - .env
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
    ports:
      - ${API_PORT}:3000
    command: npm run server
    depends_on:
      - db
  db:
    image: mongo
    container_name: db
    restart: always
    env_file:
      - .env
    ports:
      - ${DB_PORT}:27017
    volumes:
      - dbdata-volume:/data/db
    environment:
      MONGO_INITDB_DATABASE: ${MONGO_INITDB_DATABASE}
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}

volumes:
  dbdata-volume:
